# -*- coding: utf-8 -*-
"""deepLearningProjet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcPSRG3lW64eAZSRzs1reNRmZbSKWC1Z
"""

'''
Comparaison des performances de 3 modèles de Deep Learning pour la tache de classification binraire de séries temporelles ECG200:
  - MLP
  - CNN
  - RNN

Etude comparative de:
  - performances (taille modèles, temps d'entrainement, temps d'inférence)
  - précision (matrice de confusion, f1, matrice de corrélation)

Potentiellement, distillation du modèle ?
'''

"""## PREPARATION DES JEUX DE DONNEES"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

"""### téléchargement"""

TRAIN_URL = "https://maxime-devanne.com/datasets/ECG200/ECG200_TRAIN.tsv"
TEST_URL = "https://maxime-devanne.com/datasets/ECG200/ECG200_TEST.tsv"

ecg200_train_df = pd.read_csv(TRAIN_URL, sep='\t', header=None)
ecg200_test_df = pd.read_csv(TEST_URL, sep='\t', header=None)

"""### chargement"""

# 1ère colonne = classe, reste = série temporelle
y_train = ecg200_train_df.iloc[:, 0]
x_train = ecg200_train_df.iloc[:, 1:]

y_test = ecg200_test_df.iloc[:, 0]
x_test = ecg200_test_df.iloc[:, 1:]

print("Séries temporelles d'entraînement :", x_train.shape)
print("Séries temporelles de test :", x_test.shape)

CLASSES = {
    'Normal': {
        'value': 1,
        'color': "rgba(255, 0, 0, 0.6)",
        'label': 'Normal',
    },
    'Infarctus': {
        'value': -1,
        'color': "rgba(0, 0, 255, 0.6)",
        'label': 'Infarctus',
    }
}
# helpers
NORMAL_CLASS_VALUE = CLASSES['Normal']['value']
NORMAL_CLASS_COLOR = CLASSES['Normal']['color']
NORMAL_CLASS_LABEL = CLASSES['Normal']['label']
INFRACT_CLASS_VALUE = CLASSES['Infarctus']['value']
INFRACT_CLASS_COLOR = CLASSES['Infarctus']['color']
INFRACT_CLASS_LABEL = CLASSES['Infarctus']['label']

# on enregistre la position des différentes classes
x_train_normal_idx = y_train.loc[y_train == NORMAL_CLASS_VALUE].index
x_train_infarct_idx = y_train.loc[y_train == INFRACT_CLASS_VALUE].index
x_test_normal_idx = y_test.loc[y_test == NORMAL_CLASS_VALUE].index
x_test_infarct_idx = y_test.loc[y_test == INFRACT_CLASS_VALUE].index

print("TRAIN - # séries normales  :", len(x_train_normal_idx))
print("TRAIN - # séries infarctus :", (len(x_train) - len(x_train_normal_idx)))
print("------------------")
print("TEST - # séries normales  :",  len(x_test_normal_idx))
print("TEST - # séries infarctus :",  (len(x_test) - len(x_test_normal_idx)))

"""### visualisation"""

NUM_TO_VISUALIZE =  100

def prepare_plotly_data_from_indices(df, indices, class_name):
    subset = df.loc[indices].head(NUM_TO_VISUALIZE)
    # add id field
    subset['ID'] = [f"{class_name}_{i}" for i in range(len(subset))]
    # transform to long-format (columns: id, temps, amplitude, classe)
    melted = subset.melt(id_vars=['ID'], var_name='Temps', value_name='Amplitude')
    melted['Classe'] = class_name
    return melted

df_plot = pd.concat([
    prepare_plotly_data_from_indices(x_train, x_train_normal_idx, NORMAL_CLASS_LABEL),
    prepare_plotly_data_from_indices(x_train, x_train_infarct_idx, INFRACT_CLASS_LABEL)
])

fig = px.line(df_plot, x='Temps', y='Amplitude', color='Classe', line_group='ID',
              color_discrete_map={NORMAL_CLASS_LABEL: NORMAL_CLASS_COLOR, INFRACT_CLASS_LABEL: INFRACT_CLASS_COLOR},
              title="Visualisation des ECGs (train)",
              template="plotly_white")

fig.update_layout(xaxis_title="Temps", yaxis_title="Amplitude de l'activité électrique")
fig.update_traces(line=dict(width=1))
fig.show()

mean_per_class_normal = x_train.loc[x_train_normal_idx].mean(axis=1)
mean_per_class_infarct = x_train.loc[x_train_infarct_idx].mean(axis=1)
print('Moyenne des ECGs des séries normales: ', mean_per_class_normal.mean())
print('Moyenne des ECGs des séries infarctus: ', mean_per_class_infarct.mean())

def plot_variability(mean, std, name, color):
    fig = go.Figure()
    time_axis = list(range(len(mean)))

    # Enveloppe de l'écart-type
    fig.add_trace(go.Scatter(x=time_axis, y=mean+std, mode='lines', line=dict(width=0), showlegend=False))
    fig.add_trace(go.Scatter(x=time_axis, y=mean-std, mode='lines', line=dict(width=0), fill='tonexty', fillcolor=color.replace('0.6', '0.2'), name='Écart type'))

    # Ligne de la moyenne
    fig.add_trace(go.Scatter(x=time_axis, y=mean, name=f"Moyenne", line=dict(color=color, width=3)))

    fig.update_layout(title=f"Variabilité des ECGs {name}",
                      xaxis_title="Temps",
                      yaxis_title="Amplitude",
                      template="plotly_white")
    fig.show()

mean_per_timestamp_normal = x_train.loc[x_train_normal_idx].mean(axis=0)
std_per_timestamp_normal = x_train.loc[x_train_normal_idx].std(axis=0)
mean_per_timestamp_infarct = x_train.loc[x_train_infarct_idx].mean(axis=0)
std_per_timestamp_infarct = x_train.loc[x_train_infarct_idx].std(axis=0)

plot_variability(mean_per_timestamp_normal, std_per_timestamp_normal, NORMAL_CLASS_LABEL, NORMAL_CLASS_COLOR)
plot_variability(mean_per_timestamp_infarct, std_per_timestamp_infarct, INFRACT_CLASS_LABEL, INFRACT_CLASS_COLOR)

"""### pré-traitement"""

x_train_std = (x_train - x_train.mean()) / x_train.std()
x_test_std = (x_test - x_train.mean()) / x_train.std()

# one hot encoding sur y
y_train = pd.get_dummies(y_train)
y_test = pd.get_dummies(y_test)

y_train

"""## MODELE MLP + ENTRAINEMENT"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras import regularizers

input_size = 96
hidden_states_sizes = [30,20]
output_size = 2

# init model
mlp_model = models.Sequential(name='MLP')

# input
mlp_model.add(layers.Input(shape=(input_size,)))

# deep layers
for idx,h in enumerate(hidden_states_sizes):
    mlp_model.add(layers.Dense(h, activation='relu', name='Dense_'+str(idx), kernel_regularizer=regularizers.l2(0.001)))
    mlp_model.add(layers.Dropout(0.3))


# output
mlp_model.add(layers.Dense(output_size, activation='softmax',name='Output'))

mlp_model.summary()

mlp_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

import time
t_start = time.time()
history = mlp_model.fit(
    x_train_std,
    y_train,
    validation_data=(x_test_std, y_test),
    epochs=50,
    batch_size=16
)
# add criteria for stopping !!!!!!!!!!
train_time_mlp = time.time() - t_start

t_inf_start = time.time()

# Plot accuracy
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('MLP Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

# Plot loss
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('MLP Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.show()

test_loss_mlp, test_acc_mlp = mlp_model.evaluate(x_test_std, y_test)
inf_time_mlp = (time.time() - t_inf_start) * 1000
print("Test Accuracy MLP:", test_acc_mlp)

"""## MODELE CNN + ENTRAINEMENT"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Activation


x_train_std = (x_train - x_train.mean()) / x_train.std()
x_test_std = (x_test - x_train.mean()) / x_train.std()

x_train_cnn = x_train_std.values.reshape(-1, 96, 1)
x_test_cnn = x_test_std.values.reshape(-1, 96, 1)


input_shape = (96, 1)
input_layer = tf.keras.layers.Input(input_shape)

hidden_conv_layer_1 = tf.keras.layers.Conv1D(filters=16, kernel_size=3, padding='same', activation='relu')(input_layer)
pooling_1 = tf.keras.layers.MaxPooling1D(pool_size=2)(hidden_conv_layer_1)
dropout_1 = tf.keras.layers.Dropout(0.3)(pooling_1)

hidden_conv_layer_2 = tf.keras.layers.Conv1D(filters=32, kernel_size=5, padding='same', activation='relu')(dropout_1)
pooling_2 = tf.keras.layers.MaxPooling1D(pool_size=2)(hidden_conv_layer_2)
dropout_2 = tf.keras.layers.Dropout(0.4)(pooling_2)
# adding a dense layer

flatten = tf.keras.layers.Flatten()(dropout_2)
output = tf.keras.layers.Dense(2, activation='softmax')(flatten)

model_cnn = tf.keras.Model(inputs=input_layer, outputs=output)
model_cnn.summary()

model_cnn.compile(loss='categorical_crossentropy',optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy'])


model_checkpoint = tf.keras.callbacks.ModelCheckpoint('best-model.h5',monitor='val_loss',save_best_only=True)

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

t_start = time.time()
history_cnn = model_cnn.fit(x_train_cnn,y_train,batch_size=16,epochs=100,validation_split=0.3,callbacks=[model_checkpoint, early_stop],verbose=1)
train_time_cnn = time.time() - t_start

plt.figure()
plt.plot(history_cnn.history['loss'], label='Train Loss')
plt.plot(history_cnn.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.savefig('epoch-loss.pdf')
plt.show()


plt.figure()
plt.plot(history_cnn.history['accuracy'], label='Train Accuracy')
plt.plot(history_cnn.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

t_inf_start = time.time()
test_loss_cnn, test_acc_cnn = best_model.evaluate(x_test_cnn, y_test)
inf_time_cnn = (time.time() - t_inf_start) * 1000
print("Test Accuracy CNN:", test_acc_cnn)

"""## MODELE RNN + ENTRAINEMENT"""

import tensorflow as tf
from tensorflow.keras import layers, models

x_train_rnn = x_train_std.values.reshape(-1, 96, 1)
x_test_rnn  = x_test_std.values.reshape(-1, 96, 1)

input_shape = (96, 1)
input_layer = tf.keras.layers.Input(input_shape)

lstm_1 = layers.LSTM(64, return_sequences=True, recurrent_dropout=0.2)(input_layer)

dropout_1 = layers.Dropout(0.3)(lstm_1)

lstm_2 = layers.LSTM(32, return_sequences=False, recurrent_dropout=0.2)(dropout_1)
dropout_2 = layers.Dropout(0.3)(lstm_2)

output = layers.Dense(2, activation='softmax')(dropout_2)

model_rnn = tf.keras.Model(inputs=input_layer, outputs=output)
model_rnn.summary()

import numpy as np

def augment_ecg(X, y, noise_level=0.01, shift_max=5):
    X_aug = []
    y_aug = []

    for i in range(len(X)):
        signal = X[i]
        label = y[i]


        X_aug.append(signal)
        y_aug.append(label)


        noisy = signal + np.random.normal(0, noise_level, signal.shape)
        X_aug.append(noisy)
        y_aug.append(label)


        shift = np.random.randint(-shift_max, shift_max)
        shifted = np.roll(signal, shift)
        X_aug.append(shifted)
        y_aug.append(label)

    return np.array(X_aug), np.array(y_aug)


x_train_rnn_aug, y_train_aug = augment_ecg(x_train_rnn, y_train.values)
print("Taille originale :", x_train_rnn.shape)
print("Taille augmentée :", x_train_rnn_aug.shape)

class_weight = {-1: 1.0, 1: 2.23}

model_rnn.compile(
    loss='categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    metrics=['accuracy']
)

model_checkpoint_rnn = tf.keras.callbacks.ModelCheckpoint(
    'best-model-rnn.keras',
    monitor='val_loss',
    save_best_only=True
)

early_stop_rnn = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=25,
    restore_best_weights=True
)

import time
t_start = time.time()

history_rnn = model_rnn.fit(
    x_train_rnn_aug,
    y_train_aug,
    batch_size=32,
    epochs=100,
    validation_split=0.2,
    class_weight=class_weight,
    callbacks=[model_checkpoint_rnn, early_stop_rnn],
    verbose=1
)

train_time_rnn = time.time() - t_start
print(f"\nTemps d'entraînement RNN : {train_time_rnn:.2f}s")


plt.figure()
plt.plot(history_rnn.history['loss'], label='Train Loss')
plt.plot(history_rnn.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('RNN Loss')
plt.legend()
plt.grid(True)
plt.show()

plt.figure()
plt.plot(history_rnn.history['accuracy'], label='Train Accuracy')
plt.plot(history_rnn.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('RNN Accuracy')
plt.legend()
plt.grid(True)
plt.show()


t_inf_start = time.time()
test_loss_rnn, test_acc_rnn = model_rnn.evaluate(x_test_rnn, y_test)
inf_time_rnn = (time.time() - t_inf_start) * 1000

print("Test Accuracy RNN :", test_acc_rnn)
print(f"Temps d'inférence ({len(x_test_rnn)} signaux) : {inf_time_rnn:.2f} ms")
print(f"Temps d'inférence par signal : {inf_time_rnn/len(x_test_rnn):.3f} ms")

"""### COMPARAISON AVEC L'ETAT DE L'ART





"""

"""### COMPARAISON AVEC L'ETAT DE L'ART"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

results = {
    'Modèle': ['MLP ', 'CNN ', 'RNN'],
    'Accuracy (%)': [
        round(test_acc_mlp * 100, 2),
        round(test_acc_cnn * 100, 2),
        round(test_acc_rnn * 100, 2)
    ]
}

df_results = pd.DataFrame(results)



plt.figure(figsize=(8, 4))
bars = plt.barh(df_results['Modèle'], df_results['Accuracy (%)'], color=['#4C72B0', '#55A868', '#C44E52'])
plt.xlabel('Accuracy (%)')
plt.title('Comparaison des 3 modèles — ECG200')
plt.xlim(60, 100)

for bar, val in zip(bars, df_results['Accuracy (%)']):
    plt.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height()/2,
             f'{val:.1f}%', va='center', fontsize=10)

plt.tight_layout()
plt.grid(axis='x', alpha=0.3)
plt.show()


best_model_name = df_results.loc[df_results['Accuracy (%)'].idxmax(), 'Modèle']
best_acc = df_results['Accuracy (%)'].max()

print(f"\nMeilleur modèle : {best_model_name} avec {best_acc:.1f}%")
print("""
Analyse :
- Le MLP est le plus simple mais performe bien sur ce petit dataset (100 échantillons).
- Le CNN capture bien les patterns locaux du signal ECG mais nécessite plus de données.
- Le RNN/LSTM est adapté aux séries temporelles mais souffre du manque de données.
- Sur un dataset plus grand, CNN et RNN surpasseraient probablement le MLP.
""")

"""## EVALUATION DES PERFORMANCES"""

import pandas as pd
import matplotlib.pyplot as plt


perf = {
    'Modèle': ['MLP', 'CNN', 'RNN/LSTM'],
    'Paramètres': [
        mlp_model.count_params(),
        model_cnn.count_params(),
        model_rnn.count_params()
    ],
    'Temps entraînement (s)': [
        round(train_time_mlp, 2),
        round(train_time_cnn, 2),
        round(train_time_rnn, 2)
    ],
    'Temps inférence (ms)': [
        round(inf_time_mlp, 2),
        round(inf_time_cnn, 2),
        round(inf_time_rnn, 2)
    ],
    'Temps / signal (ms)': [
        round(inf_time_mlp / len(x_test_std), 3),
        round(inf_time_cnn / len(x_test_cnn), 3),
        round(inf_time_rnn / len(x_test_rnn), 3)
    ],
    'Accuracy (%)': [
        round(test_acc_mlp * 100, 2),
        round(test_acc_cnn * 100, 2),
        round(test_acc_rnn * 100, 2)
    ]
}

df_perf = pd.DataFrame(perf)


fig, axes = plt.subplots(1, 3, figsize=(15, 5))
colors = ['#4C72B0', '#55A868', '#C44E52']


axes[0].bar(df_perf['Modèle'], df_perf['Paramètres'], color=colors)
axes[0].set_title('Nombre de paramètres')
axes[0].set_ylabel('Paramètres')
axes[0].grid(axis='y', alpha=0.3)
for i, v in enumerate(df_perf['Paramètres']):
    axes[0].text(i, v + 100, str(v), ha='center', fontsize=9)

axes[1].bar(df_perf['Modèle'], df_perf['Temps entraînement (s)'], color=colors)
axes[1].set_title('Temps d\'entraînement (s)')
axes[1].set_ylabel('Secondes')
axes[1].grid(axis='y', alpha=0.3)
for i, v in enumerate(df_perf['Temps entraînement (s)']):
    axes[1].text(i, v + 0.1, f'{v}s', ha='center', fontsize=9)

# Accuracy
axes[2].bar(df_perf['Modèle'], df_perf['Accuracy (%)'], color=colors)
axes[2].set_title('Accuracy (%)')
axes[2].set_ylabel('Accuracy (%)')
axes[2].set_ylim(60, 100)
axes[2].grid(axis='y', alpha=0.3)
for i, v in enumerate(df_perf['Accuracy (%)']):
    axes[2].text(i, v + 0.3, f'{v}%', ha='center', fontsize=9)

plt.suptitle('Comparaison des performances des 3 modèles', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()


print("""
Analyse :
- Le MLP est le plus léger (moins de paramètres) et le plus rapide à entraîner.
- Le CNN a plus de paramètres mais un bon compromis vitesse/précision.
- Le RNN/LSTM est le plus lourd et le plus lent à cause des cellules récurrentes.
- Sur un petit dataset, un modèle simple comme le MLP peut suffire.
""")

"""## EVALUATION DE LA PRECISION"""


